name: Pull Requests

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Configure the enviroment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Pre-check the json
    - name: Json Precheck
      run: python precheck.py