name: When Push

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Configure the enviroment
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Pre-check the json
    - name: Json Precheck
      run: python precheck.py

    # Dispatch the parser
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTION_SCRIPT }}
        event-type: ost-data-update-event
        repository: BA-OST-Index/ost_data_parser